# Generated by Django 5.0.1 on 2024-01-30 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('slug', models.SlugField(max_length=55, unique=True, verbose_name='Артикул')),
                ('avatar', models.ImageField(blank=True, default='default.jpg', upload_to='images/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение записи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('YES', 'В наличии'), ('NO', 'Скоро на складе')], default='YES', max_length=10, verbose_name='Статус товара')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Колличество')),
                ('price', models.DecimalField(decimal_places=0, default=1990, max_digits=8, verbose_name='Цена')),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name', '-publish', 'status'], name='product_name_df5a3b_idx')],
            },
        ),
    ]
