# Generated by Django 5.0.1 on 2024-02-19 14:19

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='Категория'),
        ),
    ]
